# setup_skill.py — Install or update the user-level Claude Code skill for the alc CLI.
# Writes ~/.claude/skills/alc/SKILL.md so an in-editor Claude agent knows how to drive
# the alc CLI surface.  Project-agnostic; version-stamped; idempotent.
from __future__ import annotations

from pathlib import Path

try:
    from importlib.metadata import version as _pkg_version, PackageNotFoundError
except ImportError:  # Python < 3.8 shim (should never occur for us)
    PackageNotFoundError = Exception  # type: ignore[misc,assignment]
    def _pkg_version(_name: str) -> str:  # type: ignore[misc]
        raise PackageNotFoundError(_name)


# ---------------------------------------------------------------------------
# Version resolution
# ---------------------------------------------------------------------------

def _resolve_version() -> str:
    """Return the installed distribution version for 'alc', or '0.0.0' as fallback."""
    try:
        return _pkg_version("alc")
    except Exception:
        return "0.0.0"


# ---------------------------------------------------------------------------
# SKILL.md template
# ---------------------------------------------------------------------------

SKILL_BODY_TEMPLATE: str = """\
---
name: alc
description: >
  Use when working in a repository that contains a `.alc/` Operator Layer
  (Agentic Layer Compiler). Drive the `alc` CLI to run verified,
  control-plane-enforced work — lint, run, flow, conduct, specialist, tick —
  instead of editing files directly when the task fits a Blueprint or Flow.
---

## What ALC is

ALC is a control plane that enforces best practices (Assurance Loop checks,
Policy Gate, Scorecard, optional git-worktree isolation) OUTSIDE the model.
You drive it via the `alc` CLI; the control plane handles policy, verification,
and repair — you just supply the task description.

## Discover this project's capabilities

Run `alc lint` to validate the Operator Layer, then read:

- `.alc/manifest.yaml` — engine config and directory layout
- `.alc/blueprints/` — available Blueprints (chore, bug, feature, plan, …)
- `.alc/flows/` — available Flows (ship, …)
- `.alc/specialists/` — available Specialists (if any)

## Commands

- `alc run <blueprint> "<task>" [--engine N] [--isolate]`
  Run a single Blueprint as one mandate (Assurance Loop runs its checks,
  repairs on failure). Use `--isolate` to contain edits to a temporary
  git-worktree branch.

- `alc flow <flow> "<task>" [--isolate]`
  Run a multi-stage pipeline (e.g. plan → build). Stages share one worktree
  when `--isolate` is set.

- `alc conduct "<goal>" [--enqueue]`
  Let ALC pick which Flow(s) to run from a high-level goal. `--enqueue`
  queues them for `alc tick` instead of running immediately.

- `alc specialist <name> "<task>"`
  Run an area Specialist (Recall → Act → Learn over its Knowledge File).

- `alc tick`
  Drain the task queue (Unattended Mode). Designed for cron; safe to call
  manually too.

## Why prefer ALC over direct edits

Delegating verifiable work to `alc run` / `alc flow` runs the declared checks
and only reports success when they pass — stronger than editing files directly.
The Scorecard records Span / Passes / Streak / Touch so you can track quality
over time.  Use `--isolate` to contain edits to a temporary git-worktree branch
and review before merging.

Generated by alc setup for alc {version}.
"""


# ---------------------------------------------------------------------------
# Public API
# ---------------------------------------------------------------------------

def render_skill(version: str) -> str:
    """Return the full SKILL.md text with the given version stamp."""
    return SKILL_BODY_TEMPLATE.format(version=version)


def install_skill(
    skills_root: Path | None = None,
    version: str | None = None,
) -> tuple[Path, bool]:
    """Write the ALC skill to skills_root/alc/SKILL.md.

    Args:
        skills_root: Parent directory for skill namespaces.  Defaults to
            ``~/.claude/skills``.
        version: Version string to embed in the skill.  Defaults to the
            installed distribution version (``importlib.metadata``).

    Returns:
        A ``(path, changed)`` tuple where *path* is the target file and
        *changed* is ``True`` when the file was written (created or updated)
        or ``False`` when the existing content was already identical.
    """
    if skills_root is None:
        skills_root = Path.home() / ".claude" / "skills"
    if version is None:
        version = _resolve_version()

    target = skills_root / "alc" / "SKILL.md"
    content = render_skill(version)

    if target.exists() and target.read_text() == content:
        return target, False

    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text(content)
    return target, True
